### ISSUE TITLE
G&G scale configuration translation

### ISSUE THREAD

**Issue by eamars** [ripper121/RoboTrickler#2]
I just translated the G&G scale configuration from the manual written in Chinese. Hope this will help you too. 

 | Variable | Name                                    | Recommended Value                        | All Options                                                                                                                                                    |
| -------- | --------------------------------------- | ---------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- |
 | C1       | Sensitivity                             | 1                                        | 0 (highest)<br>1<br>2<br>3<br>4<br>5 (lowest, default)                                                                                                         |
 | C2       | Averaging Window (filter)               | 1                                        | 0 (shortest)<br>1<br>2<br>3<br>4 (longest, default)                                                                                                            |
| C3       | Serial Settings                         | 6                                        | 0 (9600 baud, stream mode)<br>1 (9600 baud, auto print on stable)<br>2 (600 baud, default)<br>3 (1200 baud)<br>4 (2400 baud)<br>5 (4800 baud)<br>6 (9600 baud) |
| C4       | Serial Comm Identification              | 33 (press COUNT to loop through options) | 27 (default)                                                                                                                                                   |
| C5       | Backlight                               | 0                                        | 0 (always on, default)<br>1 (auto)<br>2 (off)                                                                                                                  |
| C6       | Calibration | 0                                        | 0 (enable internal calibration)<br>1 (disable internal calibration)<br>2 (disable default internal calibration)                                                |

BTW I think C3 should be set to 0 and C4 to kept at 27.

**Comment by ripper121** [comment]
0 (9600 baud, stream mode)
1 (9600 baud, auto print on stable)

Cool thats new to me. I updated the Wiki
Bot not sure if this will Match to any Model. 
Do you have found the original Manufacturer homepage?

C4 is not relevant for the Robo-Trickler. Im searching for the Decimal Dot, so i can get the Integers and decimal places part.
That works for almos any Scale Protocol so far.

```
...
    int separator = String(buff).indexOf('.');

    int N10P3 = 0;
    int N10P2 = 0;
    int N10P1 = 0;
    int N10N1 = 0;
    int N10N2 = 0;
    int N10N3 = 0;

    if (separator != -1)
    {
      N10P3 = (buff[separator - 3] > 0x30) ? (buff[separator - 3] - 0x30) : 0;
      N10P2 = (buff[separator - 2] > 0x30) ? (buff[separator - 2] - 0x30) : 0;
      N10P1 = (buff[separator - 1] > 0x30) ? (buff[separator - 1] - 0x30) : 0;
      N10N1 = (buff[separator + 1] > 0x30) ? (buff[separator + 1] - 0x30) : 0;
      N10N2 = (buff[separator + 2] > 0x30) ? (buff[separator + 2] - 0x30) : 0;
      N10N3 = (buff[separator + 3] > 0x30) ? (buff[separator + 3] - 0x30) : 0;

      weight = N10P3 * 100.0;
      weight += N10P2 * 10.0;
      weight += N10P1 * 1.0;
      weight += (N10N1 == 0) ? (0.0) : (N10N1 / 10.0);
      weight += (N10N2 == 0) ? (0.0) : (N10N2 / 100.0);
      weight += (N10N3 == 0) ? (0.0) : (N10N3 / 1000.0);
...
```

**Comment by eamars** [comment]
Here are some update after talking to other G&G users

1. For C4 I think the serial identification is copied from your page https://github.com/ripper121/RoboTrickler/wiki#einstellungen
2. For C3, It looks like it depending on the model. I'm using G&G JJ223BF and it has the option of 0 and 1. For JJ100B the 0 and 1 are not available. 

The above table is translated from the physical copy of the manual that came with the JJ223BF. The settings applies to

- JJ124BF
- JJ224BF
- JJ324BF
- JJ223BF
- JJ232BF
- JJ523BF
- JJ623BF
- JJ1023BF
- JJ1523BF

**Comment by ripper121** [comment]
Ok thank you for your Help and these Infos :)
Can I close this?

**Comment by eamars** [comment]
Yes sure. 

Regarding the decoder, you might be able to use `strtof` to convert the decimal string into the floating point number. That could save you some lines of code.

**Comment by ripper121** [comment]
Not sure if it is a good idea to use strtof in an µC enviroment, I feel saver right now with how I have done it :)
